const GET_USER_AUTH_INFO = "GET_USER_AUTH_INFO"
const GET_USER_AUTH_INFO_SUCCESS = "GET_USER_AUTH_INFO_SUCCESS"

export const UserInfoActionTypes = {
  GET_USER_AUTH_INFO,
  GET_USER_AUTH_INFO_SUCCESS
}
