const GET_USER_AUTH_INFO = "GET_USER_AUTH_INFO"
const GET_USER_AUTH_INFO_SUCCESS = "GET_USER_AUTH_INFO_SUCCESS"
const CLEAR_LOGGIN_REDUCER = "CLEAR_LOGGIN_REDUCER"
const STORE_NUMBER = "STORE_NUMBER"

export const UserInfoActionTypes = {
  GET_USER_AUTH_INFO,
  GET_USER_AUTH_INFO_SUCCESS,
  CLEAR_LOGGIN_REDUCER,
  STORE_NUMBER
}
