const POST_SIGNUP_ACTION = "POST_SIGNUP_ACTION"
const POST_SIGNUP_ACTION_SUCCESS = "POST_SIGNUP_ACTION_SUCCESS"

export const SignUpActionTypes = {
  POST_SIGNUP_ACTION,
  POST_SIGNUP_ACTION_SUCCESS
}
