const POST_SIGNUP_ACTION = "POST_SIGNUP_ACTION"
const POST_SIGNUP_ACTION_SUCCESS = "POST_SIGNUP_ACTION_SUCCESS"
const POST_SIGNUP_ACTION_FAILED = "POST_SIGNUP_ACTION_FAILED"

export const SignUpActionTypes = {
  POST_SIGNUP_ACTION,
  POST_SIGNUP_ACTION_SUCCESS,
  POST_SIGNUP_ACTION_FAILED
}
