const POST_SIGNIN_ACTION = "POST_SIGNIN_ACTION"
const POST_SIGNIN_ACTION_SUCCESS = "POST_SIGNIN_ACTION_SUCCESS"
const POST_SIGNIN_ACTION_FAILED = "POST_SIGNIN_ACTION_FAILED"
const FB_SIGN_IN = "FB_SIGN_IN"
const FB_SIGN_IN_SUCCESS = "FB_SIGN_IN_SUCCESS"
const CLEAR_SIGNIN_STATE = "CLEAR_SIGNIN_STATE"

export const SignInActionTypes = {
  POST_SIGNIN_ACTION,
  POST_SIGNIN_ACTION_SUCCESS,
  POST_SIGNIN_ACTION_FAILED,
  FB_SIGN_IN,
  FB_SIGN_IN_SUCCESS,
  CLEAR_SIGNIN_STATE
}
