const POST_SIGNIN_ACTION = "POST_SIGNIN_ACTION"
const POST_SIGNIN_ACTION_SUCCESS = "POST_SIGNIN_ACTION_SUCCESS"

export const SignInActionTypes = {
  POST_SIGNIN_ACTION,
  POST_SIGNIN_ACTION_SUCCESS
}
